version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payload
    volumes:
      - postgres-data:/var/lib/postgresql/data

  payload:
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/payload
      PAYLOAD_PUBLIC_SERVER_URL: http://localhost:3000
    depends_on:
      - postgres

volumes:
  postgres-data:
